Recursive mkdir to allow path.sep in a path
sindresorhus/tempy pull request #44
Opened 2022-08-09 23:02 UTC by justinormont

From https://github.com/sindresorhus/tempy/issues/43:

> Prefix which includes a `path.sep` fails.
> 
> ### Repro
> This fails as the path will include a `path.sep`:
> ```js
> const uuid = 'xyz';
> const prefixForRun = path.join('runs', `run_${uuid}`);
> const outputFolder = temporaryDirectory({prefix: prefixForRun});
> ```
> 
> This call results in a path of:
> '/private/var/folders/6t/frtzt7q96fv9xjqp3knl3vqh0000gn/T/runs/run_xyz'
> 
> The mkdir for `run_xyz` fails since the parent, `/private/var/folders/6t/frtzt7q96fv9xjqp3knl3vqh0000gn/T/runs/`, does not exist.
> 
> ### Error
> ```
> Error: ENOENT: no such file or directory, mkdir '/private/var/folders/6t/frtzt7q96fv9xjqp3knl3vqh0000gn/T/runs/run_xyz'
>     at Object.mkdirSync (node:fs:1324:3)
> ```
> 
> ### Solution
> In mkdir, add the `{recursive: true}` option.
> 
> ### Discussion
> Incidentally, fixing this gives an indirect method of https://github.com/sindresorhus/tempy/issues/35, as my intention was similar. To organize my temp files/folders for later cleanup, I was adding a parent folder to my requested temp folder.

Closes https://github.com/sindresorhus/tempy/issues/43

2022-08-16 19:06 UTC, justinormont commented
@sindresorhus: Can you take a look at my short PR?

2022-08-30 11:11 UTC, sindresorhus requested changes

2022-08-30 11:11 UTC, sindresorhus commented on test.js
> +	t.true(path.dirname(temporaryDirectory({prefix})).split(path.sep).pop() === prefix.split(path.sep)[0]);
Better to put this into a separate test.

2022-08-30 11:11 UTC, sindresorhus commented on test.js
> +	t.true(path.dirname(temporaryDirectory({prefix})).split(path.sep).pop() === prefix.split(path.sep)[0]);
Use `t.is`

2022-08-30 11:12 UTC, sindresorhus commented
I don't think this is a good idea. What if you want just a parent directory and not a name prefix. That becomes awkward. I think it would be better to introduce a new option that worked for both file and directory called `parentDirectory`.

2023-06-20 12:43 UTC, sindresorhus commented
Closing for lack of activity.

https://github.com/sindresorhus/tempy/issues/46

2023-06-20 12:43 UTC, closed without merging